"""
Trading Signals Endpoints

Provides access to trading signals generated by strategies.
Signals can be stored in SQLite or returned as mock data.
"""

from fastapi import APIRouter, Header
from app.auth import session_manager
import sqlite3
import os
import json


# Create router with signals tag
router = APIRouter(tags=["signals"])


# Database path for signals storage
DB_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "..", "data", "dashboard.db")


def get_db():
    """
    Get a database connection with row factory.
    
    Returns:
        sqlite3.Connection: Database connection
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


# Mock signals for demonstration
MOCK_SIGNALS = [
    {
        "id": 1,
        "symbol": "RELIANCE",
        "signal_type": "BUY",
        "strategy": "RSI Mean Reversion",
        "trigger_price": 2480.00,
        "triggered_at": "2025-03-27T10:00:00",
        "status": "ACTIVE",
        "metadata": {"rsi": 28, "bb_position": "oversold"}
    },
    {
        "id": 2,
        "symbol": "HDFCBANK",
        "signal_type": "SELL",
        "strategy": "SMA Crossover",
        "trigger_price": 1720.00,
        "triggered_at": "2025-03-27T09:30:00",
        "status": "ACTIVE",
        "metadata": {"fast_sma": 1710, "slow_sma": 1680}
    },
    {
        "id": 3,
        "symbol": "INFY",
        "signal_type": "BUY",
        "strategy": "EMA Crossover",
        "trigger_price": 1430.00,
        "triggered_at": "2025-03-26T14:00:00",
        "status": "EXPIRED",
        "metadata": {"ema_12": 1435, "ema_26": 1420}
    },
]


@router.get("/signals")
async def get_signals(x_session_id: str = Header(alias="X-Session-ID")):
    """
    Get all trading signals.
    
    Returns active and expired signals from the database,
    falling back to mock data if database is unavailable.
    
    Args:
        x_session_id: Session ID from header for authentication
        
    Returns:
        List of trading signals with metadata
    """
    if not session_manager.validate_session(x_session_id):
        return {"error": "Not authenticated"}
    
    try:
        conn = get_db()
        c = conn.cursor()
        c.execute("SELECT * FROM signals ORDER BY triggered_at DESC LIMIT 50")
        rows = c.fetchall()
        conn.close()
        
        if rows:
            return [
                {
                    "id": row[0],
                    "symbol": row[1],
                    "signal_type": row[2],
                    "strategy": row[3],
                    "trigger_price": row[4],
                    "triggered_at": row[5],
                    "status": row[6],
                    "metadata": json.loads(row[7]) if row[7] else None
                }
                for row in rows
            ]
    except:
        pass
    
    return MOCK_SIGNALS
